### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by williamli2021** [filswan/go-swan-provider#180] opened 2022-09-26 23:27 UTC
I got the following error while running install.sh for release 2.0:

time="2022-09-26 16:26:34.261" level=error msg="Post \"http://10.1.18.167:1234/rpc/v0\": dial tcp 10.1.18.167:1234: connect: connection refused" func=httpRequest file="restful.go:81"
time="2022-09-26 16:26:34.261" level=error msg="unexpected end of JSON input" func=GetFieldFromJson file="json.go:12"
time="2022-09-26 16:26:34.261" level=error msg="Failed to get result from:http://10.1.18.167:1234/rpc/v0" func=LotusGetDealStatus file="lotus.go:79"
time="2022-09-26 16:26:34.262" level=info msg="deal: bafyreiaoricgdu64cltgpdhadiwunu2eqxmhdsh53a2tdnfdqbgpl5nifa status: message:" func=LotusGetDealOnChainStatusFromDeals file="lotus.go:121"
time="2022-09-26 16:26:34.262" level=error msg="Failed to get on chain status for :bafyreiaoricgdu64cltgpdhadiwunu2eqxmhdsh53a2tdnfdqbgpl5nifa" func=StartImport file="lotus.go:45"
time="2022-09-26 16:26:34.262" level=info msg="Deal CID: bafyreiea5d6uqxldtcpa5e4dojhijvf7eiv4rp5dpkoikskk2bgbl4uq4y. File Path: /media/data/bidbot/filswan/download/64/202205/Fly-Brain-Anatomy-01/2022-01-15-00-28-13/Gen1-MCFO-part-1188.car" func=StartImport file="lotus.go:40"

**Comment by Normalnoise** [comment] 2022-09-27 02:36
@williamli2021 
It seems that swan-provider can not connect to you lotus, please check it.

Can you check you swan-provider version?  We found you are using a old version
please run `./swan-provider version`

Besides, FilSwan has release a new version [v2.0.0](https://github.com/filswan/go-swan-provider/releases/tag/v2.0.0), it includes many bug fixes, new features and improvements. You can update to the new version following the [instruction](https://github.com/filswan/go-swan-provider/issues/179)

**Comment by williamli2021** [comment] 2022-09-30 17:58
thank you @Normalnoise. I adjusted the configurations and the error went away now.

I got this new issue:

```
time="2022-09-30 10:19:46.012" level=warning msg="taskName:swan-task-e7hxvz, dealCid:bafyreihvpfl2f4q3snasanqxgm7lym372q4iw56rvi6c5xwufy4s24k3my, Import deal failed,error code:1 message:given data does not match expected commP (got: baga6ea4seaqc2tzwdsmqn7dpx4a6a4sjvvojywssj3njqnumh3zp2gvq5bm3kia, expected baga6ea4seaqmeyl7j4lb3uyy2jmpdqffe2b5d35ps7kjn5gky57apl42oj6wwga)" func=UpdateDealInfoAndLog file="common.go:247"
time="2022-09-30 10:19:46.786" level=warning msg="taskName:swan-task-e7hxvz, dealCid:bafyreihvpfl2f4q3snasanqxgm7lym372q4iw56rvi6c5xwufy4s24k3my, set status to:ImportFailed,set note to:Import deal failed,error code:1 message:given data does not match expected commP (got: baga6ea4seaqc2tzwdsmqn7dpx4a6a4sjvvojywssj3njqnumh3zp2gvq5bm3kia, expected baga6ea4seaqmeyl7j4lb3uyy2jmpdqffe2b5d35ps7kjn5gky57apl42oj6wwga),set filepath to:/media/data/bidbot/filswan/download/baga6ea4seaqmeyl7j4lb3uyy2jmpdqffe2b5d35ps7kjn5gky57apl42oj6wwga.car" func=UpdateDealInfoAndLog file="common.go:267"
```

**Comment by boqian-nbai** [comment] 2022-09-30 20:29
> thank you @Normalnoise. I adjusted the configurations and the error went away now.
> 
> I got this new issue:
> 
> ```
> time="2022-09-30 10:19:46.012" level=warning msg="taskName:swan-task-e7hxvz, dealCid:bafyreihvpfl2f4q3snasanqxgm7lym372q4iw56rvi6c5xwufy4s24k3my, Import deal failed,error code:1 message:given data does not match expected commP (got: baga6ea4seaqc2tzwdsmqn7dpx4a6a4sjvvojywssj3njqnumh3zp2gvq5bm3kia, expected baga6ea4seaqmeyl7j4lb3uyy2jmpdqffe2b5d35ps7kjn5gky57apl42oj6wwga)" func=UpdateDealInfoAndLog file="common.go:247"
> time="2022-09-30 10:19:46.786" level=warning msg="taskName:swan-task-e7hxvz, dealCid:bafyreihvpfl2f4q3snasanqxgm7lym372q4iw56rvi6c5xwufy4s24k3my, set status to:ImportFailed,set note to:Import deal failed,error code:1 message:given data does not match expected commP (got: baga6ea4seaqc2tzwdsmqn7dpx4a6a4sjvvojywssj3njqnumh3zp2gvq5bm3kia, expected baga6ea4seaqmeyl7j4lb3uyy2jmpdqffe2b5d35ps7kjn5gky57apl42oj6wwga),set filepath to:/media/data/bidbot/filswan/download/baga6ea4seaqmeyl7j4lb3uyy2jmpdqffe2b5d35ps7kjn5gky57apl42oj6wwga.car" func=UpdateDealInfoAndLog file="common.go:267"
> ```

This means the file you downloaded was not complete, probably caused by unstable network.  Please work on other deals and see if you run into the same error again.

**Comment by Normalnoise** [comment] 2022-10-01 14:56
> thank you @Normalnoise. I adjusted the configurations and the error went away now.
> 
> I got this new issue:
> 
> ```
> time="2022-09-30 10:19:46.012" level=warning msg="taskName:swan-task-e7hxvz, dealCid:bafyreihvpfl2f4q3snasanqxgm7lym372q4iw56rvi6c5xwufy4s24k3my, Import deal failed,error code:1 message:given data does not match expected commP (got: baga6ea4seaqc2tzwdsmqn7dpx4a6a4sjvvojywssj3njqnumh3zp2gvq5bm3kia, expected baga6ea4seaqmeyl7j4lb3uyy2jmpdqffe2b5d35ps7kjn5gky57apl42oj6wwga)" func=UpdateDealInfoAndLog file="common.go:247"
> time="2022-09-30 10:19:46.786" level=warning msg="taskName:swan-task-e7hxvz, dealCid:bafyreihvpfl2f4q3snasanqxgm7lym372q4iw56rvi6c5xwufy4s24k3my, set status to:ImportFailed,set note to:Import deal failed,error code:1 message:given data does not match expected commP (got: baga6ea4seaqc2tzwdsmqn7dpx4a6a4sjvvojywssj3njqnumh3zp2gvq5bm3kia, expected baga6ea4seaqmeyl7j4lb3uyy2jmpdqffe2b5d35ps7kjn5gky57apl42oj6wwga),set filepath to:/media/data/bidbot/filswan/download/baga6ea4seaqmeyl7j4lb3uyy2jmpdqffe2b5d35ps7kjn5gky57apl42oj6wwga.car" func=UpdateDealInfoAndLog file="common.go:267"
> ```

Can you check your other deals? only if one deal can be imported to `lotus-miner`, it shows that  the downloaded CAR file is not completed.

**Comment by William8Work** [comment] 2022-11-26 19:46
I confirmed that new files were able to download and deals were getting through. closing this one.

**Closed** 2022-11-26 22:18 UTC
